services:
  social_media:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - ./:/app
      - local_media:/files/media/

  db:
    image: postgres:16-alpine
    restart: on-failure
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - local_db:${PGDATA}

volumes:
  local_db:
  local_media:
