# Generated by Django 6.1.1 on 2026-09-23 07:47

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=social_media.models.ImagePath(
                    "posts/uploads/", field="title"
                ),
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                null=True,
                upload_to=social_media.models.ImagePath(
                    field="username", path_to_store="profile_picture/uploads/"
                ),
            ),
        ),
    ]
