# Generated by Django 6.1.1 on 2026-09-24 10:26

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0003_post_image_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=social_media.models.ImagePath(
                    "posts/uploads/", field="title"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
