# Generated by Django 6.1.1 on 2026-09-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0004_alter_post_image_alter_post_publish_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
