# Generated by Django 6.1.1 on 2026-09-26 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0005_post_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="following",
        ),
        migrations.CreateModel(
            name="ProfileFollowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="social_media.profile",
                    ),
                ),
                (
                    "to_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="social_media.profile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_profile", "to_profile"), name="unique_following"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_profile", models.F("to_profile")), _negated=True
                        ),
                        name="forbid_follow_yourself",
                    ),
                ],
            },
        ),
    ]
