# Generated by Django 6.1.1 on 2026-09-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0006_remove_profile_following_profilefollowing"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                related_name="followers",
                through="social_media.ProfileFollowing",
                to="social_media.profile",
            ),
        ),
    ]
