# Generated by Django 6.1.1 on 2026-09-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0007_profile_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
