# Generated by Django 6.0.8 on 2026-10-01 18:26

import social_media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media", "0008_alter_post_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=social_media.models.ImagePath(
                    field="username", path_to_store="profile_picture/uploads/"
                ),
            ),
        ),
    ]
